In [1]:
import pandas as pd
import numpy as np

In [2]:
data_orig = pd.read_csv("ARS_clean")

In [3]:
data = pd.read_csv("ARS_clean")

In [37]:
data

Rank                                               Name   Type  \
0          1  Demon Slayer: Kimetsu no Yaiba - Entertainment...     TV   
1          2                     Fruits Basket the Final Season     TV   
2          3                                    Mo Dao Zu Shi 3    Web   
3          4                   Fullmetal Alchemist: Brotherhood     TV   
4          5                Attack on Titan 3rd Season: Part II     TV   
...      ...                                                ...    ...   
13351  18491  Qin Shi Mingyue: Canghai Hengliu Xiaomeng Spec...    Web   
13352  18492                      Yi Tang Juchang: Sanguo Yanyi     TV   
13353  18493          Fenghuang Ji Xiang Yu Qingming Shanghe Tu     TV   
13354  18494                      Chengshi Jiyi Wo Men de Jieri     TV   
13355  18495  Heisei Inu Monogatari Bow: Genshi Inu Monogata...  Movie   

                                                    Tags  \
0      action adventure fantasy shounen demons histor...   
1      drama fantasy romance shoujo animaltransformat...   
2      fantasy ancientchina chineseanimation cultivat...   
3      action adventure drama fantasy mystery shounen...   
4      action fantasy horror shounen darkfantasy isol...   
...                                                  ...   
13351  action ancientchina chineseanimation historica...   
13352                                   chineseanimation   
13353      chineseanimation familyfriendly shortepisodes   
13354      chineseanimation familyfriendly shortepisodes   
13355                            comedy sliceoflife dogs   

                                                Name_new  
0      demon-slayer-kimetsu-no-yaiba-entertainment-di...  
1                         fruits-basket-the-final-season  
2                                        mo-dao-zu-shi-3  
3                        fullmetal-alchemist-brotherhood  
4                     attack-on-titan-3rd-season-part-ii  
...                                                  ...  
13351  qin-shi-mingyue-canghai-hengliu-xiaomeng-specials  
13352                       yi-tang-juchang-sanguo-yanyi  
13353          fenghuang-ji-xiang-yu-qingming-shanghe-tu  
13354                      chengshi-jiyi-wo-men-de-jieri  
13355  heisei-inu-monogatari-bow-genshi-inu-monogatar...  

[13356 rows x 5 columns]

In [5]:
# Text Vectarization
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 13500,stop_words="english")

In [6]:
cv.fit_transform(data["Tags"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
cv.fit_transform(data["Tags"]).toarray().shape

(13356, 1931)

In [8]:
vectors = cv.fit_transform(data["Tags"]).toarray()

In [9]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
cv.get_feature_names()

/Users/kishanjeo/Desktop/Anaconda3/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['15thcentury',
 '16thcentury',
 '17thcentury',
 '18thcentury',
 '19thcentury',
 'abiumeda',
 'abstract',
 'acomomota',
 'acting',
 'action',
 'adachitoka',
 'adultcouples',
 'adventure',
 'africa',
 'afro',
 'afterlife',
 'agegap',
 'agetransformation',
 'aging',
 'agriculture',
 'ahotoro',
 'ai',
 'aijiyamakawa',
 'aikokoyama',
 'aiyazawa',
 'akaakasaka',
 'akane',
 'akaneshimizu',
 'akasatana',
 'akihamaji',
 'akihisaikeda',
 'akihitotsukushi',
 'akihitoyoshitomi',
 'akikatsu',
 'akikohigashimura',
 'akiminekamijyo',
 'akimiyoshida',
 'akinobuuraku',
 'akiochiba',
 'akioyasaka',
 'akiraamano',
 'akirahiramoto',
 'akirahiro',
 'akirahiyoshimaru',
 'akirakanda',
 'akirakojima',
 'akirakurosawa',
 'akiramiyashita',
 'akiratoriyama',
 'akkisarumi',
 'alcohol',
 'alexandredumas',
 'alfredyamamoto',
 'aliceinwonderland',
 'aliens',
 'alohahiga',
 'amahara',
 'amatou',
 'america',
 'amishibata',
 'amnesia',
 'amusementpark',
 'amyuusakura',
 'ancientchina',
 'androids',
 'androphobia',
 'a

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
similarity = cosine_similarity(vectors)

In [13]:
similarity

array([[1.        , 0.19611614, 0.10482848, ..., 0.        , 0.        ,
        0.        ],
       [0.19611614, 1.        , 0.08908708, ..., 0.        , 0.        ,
        0.        ],
       [0.10482848, 0.08908708, 1.        , ..., 0.21821789, 0.21821789,
        0.        ],
       ...,
       [0.        , 0.        , 0.21821789, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.21821789, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [14]:
similarity.shape

(13356, 13356)

In [15]:
data["Name"][2334]

'Croisee in a Foreign Labyrinth'

In [16]:
data[data["Name"] == 'Demon Slayer: Kimetsu no Yaiba - Entertainment District Arc']

Rank                                               Name Type  \
0     1  Demon Slayer: Kimetsu no Yaiba - Entertainment...   TV   

                                                Tags  
0  action adventure fantasy shounen demons histor...

In [17]:
data[data["Name"] == 'Made in Abyss Movie: Dawn of the Deep Soul'].index[0]

100

In [18]:
sorted(list(enumerate(similarity[0])), reverse= True, key = lambda x: x[1])

[(0, 1.0000000000000002),
 (12, 0.8320502943378437),
 (8, 0.7627127698096902),
 (47, 0.6671243849949912),
 (3508, 0.6201736729460423),
 (6242, 0.6139406135149206),
 (2485, 0.588348405414552),
 (4082, 0.588348405414552),
 (4802, 0.588348405414552),
 (2805, 0.5853694070049636),
 (3333, 0.5661385170722979),
 (3913, 0.5661385170722979),
 (5744, 0.5661385170722979),
 (7406, 0.5661385170722979),
 (8802, 0.5661385170722979),
 (10441, 0.5661385170722979),
 (13231, 0.5661385170722979),
 (752, 0.5547001962252291),
 (3487, 0.5547001962252291),
 (250, 0.554700196225229),
 (4276, 0.554700196225229),
 (1442, 0.5241424183609591),
 (1993, 0.5241424183609591),
 (3240, 0.5241424183609591),
 (3760, 0.5241424183609591),
 (4015, 0.5241424183609591),
 (4481, 0.5241424183609591),
 (5726, 0.5241424183609591),
 (6815, 0.5241424183609591),
 (7098, 0.5241424183609591),
 (7618, 0.5241424183609591),
 (7638, 0.5241424183609591),
 (12745, 0.5241424183609591),
 (12911, 0.5241424183609591),
 (2402, 0.5188745216627709)

In [19]:
sorted(list(enumerate(similarity[0])), reverse= True,key = lambda x: x[1]) [1:6]

[(12, 0.8320502943378437),
 (8, 0.7627127698096902),
 (47, 0.6671243849949912),
 (3508, 0.6201736729460423),
 (6242, 0.6139406135149206)]

In [20]:
# For URL ---------

In [21]:
data["Name_new"] = data["Name"].apply(lambda x: x.lower())

In [22]:
# Remove Punctuation from a String
import string

data["Name_new"] = data["Name_new"].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))


In [23]:
# Removing extra spaces
data["Name_new"] = data["Name_new"].apply(lambda x: " ".join(x.split()))

In [24]:
# Replacing " " with "-"
data["Name_new"] = data["Name_new"].apply(lambda x: x.replace(" ", "-"))

In [25]:
def Recommender(user_input):
    Index_of_anime = data[data["Name"] == user_input].index[0]
    Similarity_score = similarity[Index_of_anime]
    Sorted_scores = sorted(list(enumerate(Similarity_score)),reverse = True,key= lambda x: x[1]) [1:6]
    Recommended_Anime = []
    
    for i in Sorted_scores:
        Recommended_Anime.append(data.iloc[i[0]].Name)
    return Recommended_Anime
        

In [26]:
Recommender("Mo Dao Zu Shi 3")

['Ling Yu 4th Season',
 'Ling Yu 5th Season',
 'Wangu Xian Qiong II',
 'Ling Yu 3rd Season',
 'Wangu Xian Qiong III']

In [27]:
Recommender("Yaoshenji 2nd Season")

['Yaoshenji 4th Season',
 'Yaoshenji 2nd Season',
 'Yaoshenji',
 'Yaoshenji 5th Season',
 'Star Martial God Technique']

In [28]:
Recommender("Kaibutsu-kun Movie")

['Broken Down Film',
 'Sennin Buraku',
 'Kokoro no Chikara',
 'Zhi Ren Dao Luan Ji',
 'Jinxes']

In [29]:
Recommender("Gunslinger Stratos: The Animation")

['Gunslinger Stratos: The Animation - Kikan/Kaze no Yukue',
 'Danball Senki Wars',
 'Danball Senki Wars: All Star Battle',
 'Ryuusei no Rockman',
 'Phantasy Star Online 2: Episode Oracle']

In [30]:
Recommender("Fighting Foodons")

['Vegetable Fairies N.Y.SALAD Movie',
 'Vegetable Fairies N.Y.SALAD: Quiz Theater',
 'Sore Ike! Anpanman: Omusubiman',
 'Sore Ike! Anpanman: Inochi no Hoshi no Dolly',
 'Vegetable Fairies N.Y.SALAD']

In [31]:
Recommender("Jujutsu Kaisen")

['Jujutsu Kaisen 0',
 'Ga-Rei-Zero',
 "Hell's Paradise: Jigokuraku PV",
 'Corpse Princess: Kuro',
 "JoJo's Bizarre Adventure: Phantom Blood"]

In [32]:
# ------- For home.py --------

In [33]:
#import pickle
#pickle.dump(data.to_dict(),open("data_dict.pkl","wb"))

In [34]:
#pickle.dump(similarity,open("similarity_score.pkl", "wb"))

In [35]:
#---------#